version: '2'

services:
    app:
        container_name: "student"
        build: ./app
        ports:
            - 8080:8080
            - 9990:9990
        environment:
            - MYSQL_URI=db:3306

    mysql:
        container_name: "db"
        image: mysql:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: student
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: secret
        volumes_from:
            - data

    phpmyadmin:
        container_name: "phpmyadmin"
        image: phpmyadmin/phpmyadmin
        ports:
            - 3000:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql

    data:
        image: mysql:latest
        volumes:
            - /var/lib/mysql
        command: "true"
